### ISSUE TITLE
TypeError: cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by ranabanik** [lukasz-migas/msalign#48]
```
aligner = Aligner(
    x,
    array,
    peaks,
    weights=weights,
    return_shifts=True,
    align_by_index=True,
    only_shift=True,
    method="pchip",
)

# print(aligner.peaks)
aligner.run()
aligned_array, shifts_out = aligner.align()
```

The code above generates 

```
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2019.3.1\plugins\python\helpers\pydev\pydevd.py", line 1434, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2019.3.1\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/ranab/.PyCharm2019.3/config/scratches/scratch_12.py", line 32, in <module>
    aligned_array, shifts_out = aligner.align()
TypeError: cannot unpack non-iterable NoneType object
```
Any idea how to address the issue? 
Moreover, how to define the weights of the peaks if I don't have them?

**Comment by Shivangi1010** [comment]
Does this resolved?

**Comment by Shivangi1010** [comment]
Is this resolved?
